const PLAYER_DATA = [
  {
    "timestamp": "2026-06-23 00:27:44",
    "name": "shin",
    "state": "PB",
    "age": "25-34",
    "experience": "Menos de 1 ano",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 7,
    "favorite_factions": "Hacan, Creuss, Empyrean",
    "least_favorite_factions": "Sol, Jol-Nar, Xxcha",
    "expansions": "Jogo base apenas",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "tentei jogar no tabletop e não tive uma boa experiência, a beta do bga me pareceu uma implementação melhor",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 00:28:15",
    "name": "Franck",
    "state": "RJ",
    "age": "45+",
    "experience": "Mais de 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Mentak, Yssaril, Vuil'Raith",
    "least_favorite_factions": "Creuss, Sardakk, Firmament/Obsidian",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall, Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de manhã, Sexta-feira, começando de noite, Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 00:31:20",
    "name": "",
    "state": "PE",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "8h a 9h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Arborec, Mentak, Sardakk",
    "least_favorite_factions": "Sol, Winnu, Keleres",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Não",
    "availability": "Fins de semana, começando de tarde",
    "championship_games_count": "",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 00:33:02",
    "name": "Rirom",
    "state": "SP",
    "age": "25-34",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial, Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Creuss, Mahact, Crimson",
    "least_favorite_factions": "Arborec, Saar, Sol",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall, Aliança",
    "championship_interest": "",
    "availability": "Durante a semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 00:37:54",
    "name": "Jack maneta",
    "state": "MG",
    "age": "35-44",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Sardakk, Jol-Nar, Xxcha",
    "least_favorite_factions": "Letnev, Titans, Keleres",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 01:13:24",
    "name": "Pedreira",
    "state": "SP",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "7h a 8h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Sol, Yssaril, Argent",
    "least_favorite_factions": "Mentak, Winnu, Firmament/Obsidian",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "A depender de quantas mesas terão, mas vencedores passam de fase e perdedores jogam repescagens",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 01:18:43",
    "name": "Carlos Matheus ",
    "state": "SP",
    "age": "18-24",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "8h a 9h",
    "play_partners": "Com desconhecidos em comunidades",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Creuss, Yin, Titans",
    "least_favorite_factions": "Sardakk, Naaz-Rokha",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft, Como no manual do jogo",
    "setup_preference": "Milty draft",
    "house_rules": "Nao costumo",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Formato Liga, com os 6 melhores colocados (apos 3 rodadas de partidas) disputando 2 partidas para decidir o vencedor (o que ficar com mais pontos somados dessas duas partidas ganha a liga em geral).\n\nObservação: as 3 rodadas de partidas iniciais servirao apenas como classificatoria dos 6 melhores jogadores, que sera decidida pelos jogadores que mais fizeram pontos. Apos classicar os 6 melhores jogadores, estes jogadores irão jogar 2 partidas que irá decidir de fato o ganhador.",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 01:38:34",
    "name": "Matheus",
    "state": "SP",
    "age": "25-34",
    "experience": "Menos de 1 ano",
    "games_last_year": "4 a 10",
    "play_method": "Presencial, Tabletop Simulator, Tabletop Playground, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Empyrean, Crimson, Deepwrought",
    "least_favorite_factions": "Nekro, Xxcha, Argent",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de tarde, Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 02:20:28",
    "name": "Luis",
    "state": "SP",
    "age": "18-24",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, Tabletop Simulator, Tabletop Playground, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Empyrean, Naaz-Rokha, Deepwrought",
    "least_favorite_factions": "Mentak, Xxcha, Argent",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "Já usei o tie breaker do SCPT umas duas vezes em partidas presenciais que tinham um limite de tempo.",
    "alternative_modes": "Twilight's Fall, Aliança, Cenários (ex: ordinian, liberation), Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 02:39:09",
    "name": "",
    "state": "SC",
    "age": "25-34",
    "experience": "Mais de 6 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "6h a 7h",
    "play_partners": "Com desconhecidos em comunidades",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Hacan, Winnu, Mahact",
    "least_favorite_factions": "Mentak, Yssaril, Naaz-Rokha",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "14 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "Como no manual do jogo",
    "house_rules": "Não. ",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Eliminatória simples",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 07:20:22",
    "name": "",
    "state": "RJ",
    "age": "35-44",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Hacan, Sol, Sardakk",
    "least_favorite_factions": "",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas aleatórios",
    "setup_preference": "",
    "house_rules": "Não. Absolutamente.",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 09:57:39",
    "name": "Vitor",
    "state": "RJ",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas, Espaço físico adequado para jogar",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Mahact, Naaz-Rokha, Vuil'Raith",
    "least_favorite_factions": "Arborec, L1z1x, Xxcha",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 11:57:59",
    "name": "Artur",
    "state": "MG",
    "age": "35-44",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 8,
    "favorite_factions": "Hacan, Naalu, Winnu",
    "least_favorite_factions": "Sol",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 14:52:41",
    "name": "ravi",
    "state": "MG",
    "age": "35-44",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "7h a 8h",
    "play_partners": "Com desconhecidos em comunidades",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Nekro, Naaz-Rokha, Vuil'Raith",
    "least_favorite_factions": "Arborec, Letnev, Xxcha",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft, Mapas pré-criados, Nucleus draft",
    "setup_preference": "Milty, quando coloquei pre criados, na verdade, sao mapas de torneios, com drafts pensados para o torneio.",
    "house_rules": "Nao",
    "alternative_modes": "Twilight's Fall, Aliança, Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 15:13:01",
    "name": "Lucas Melo",
    "state": "SE",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "7h a 8h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Nekro, Argent, Vuil'Raith",
    "least_favorite_factions": "Hacan",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Fins de semana, começando de tarde",
    "championship_games_count": "Ao menos 2",
    "suggestions": "Mata mata",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 17:46:07",
    "name": "",
    "state": "GO",
    "age": "25-34",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Sol, Xxcha, Yssaril",
    "least_favorite_factions": "Letnev, Argent, Nomad",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo, Mapas pré-criados",
    "setup_preference": "Manual",
    "house_rules": "Não ",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 19:50:41",
    "name": "",
    "state": "DF",
    "age": "25-34",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Presencial",
    "biggest_difficulty": "",
    "avg_duration": "8h a 9h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 8,
    "favorite_factions": "Arborec, L1z1x, Nekro",
    "least_favorite_factions": "",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Não",
    "availability": "",
    "championship_games_count": "",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 19:55:40",
    "name": "",
    "state": "DF",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Yssaril, Naaz-Rokha, Crimson",
    "least_favorite_factions": "Xxcha, Argent, Deepwrought",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft, Como no manual do jogo",
    "setup_preference": "Milty",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 21:47:17",
    "name": "Ronaldo",
    "state": "ES",
    "age": "35-44",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Saar, Mentak, Xxcha",
    "least_favorite_factions": "Arborec, Sardakk, Winnu",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "",
    "house_rules": "Nada de meinha. Quem fornece o suporte ao trono não pode recebê-lo. ",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 22:08:28",
    "name": "DENIS",
    "state": "SP",
    "age": "35-44",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Xxcha, Titans, Vuil'Raith",
    "least_favorite_factions": "Letnev, Yin, Keleres",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "Nao",
    "alternative_modes": "Twilight's Fall",
    "championship_interest": "Talvez",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 22:21:27",
    "name": "",
    "state": "DF",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 5,
    "favorite_factions": "Muaat, Sol, Titans",
    "least_favorite_factions": "Arborec, Letnev, Creuss",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "12 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "Posição e raça.",
    "house_rules": "Não",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-23 22:59:45",
    "name": "Bruno",
    "state": "MG",
    "age": "25-34",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Sol, Xxcha, Nomad",
    "least_favorite_factions": "Arborec, Mentak, Titans",
    "expansions": "Jogo base apenas",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 00:11:58",
    "name": "Fernando Carlos da Silva ",
    "state": "MG",
    "age": "45+",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Sol, L1z1x, Nekro",
    "least_favorite_factions": "Arborec, Sardakk, Yin",
    "expansions": "Jogo base apenas",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "Não ",
    "house_rules": "Não ",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de manhã, Durante a semana, começando de tarde, Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 00:54:06",
    "name": "Davi",
    "state": "SP",
    "age": "25-34",
    "experience": "Menos de 1 ano",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, BGA",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 5,
    "favorite_factions": "Jol-Nar, Xxcha, Empyrean",
    "least_favorite_factions": "Letnev, Creuss, Yin",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 06:38:10",
    "name": "Adolfo Pentagna",
    "state": "RJ",
    "age": "45+",
    "experience": "Mais de 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Presencial, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Nekro, Empyrean, Mahact",
    "least_favorite_factions": "Mentak, Xxcha, Firmament/Obsidian",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft, Nucleus draft",
    "setup_preference": "Nucleus ",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall, Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 2",
    "suggestions": "Assync pelo Discord",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 07:27:48",
    "name": "",
    "state": "RJ",
    "age": "35-44",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Twilight Wars, Async TI Discord, Boardgame Arena",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "Não jogo partidas ao vivo",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Arborec, Creuss, Vuil'Raith",
    "least_favorite_factions": "Letnev, Hacan, Winnu",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "",
    "house_rules": "Não trocar suporte ao trono, qualquer negociação somente com vizinhança ",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Ao menos 1",
    "suggestions": "Eliminatórias online e final presencial, se possível. ",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 09:29:14",
    "name": "Marcial",
    "state": "SP",
    "age": "45+",
    "experience": "Mais de 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Arborec, Creuss, Empyrean",
    "least_favorite_factions": "",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "",
    "house_rules": "Não",
    "alternative_modes": "",
    "championship_interest": "Não",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Presencial",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 09:36:25",
    "name": "fugas",
    "state": "RJ",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, Tabletop Simulator, Tabletop Playground",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Arborec, Creuss, Naaz-Rokha",
    "least_favorite_factions": "Xxcha, Firmament/Obsidian, Last Bastion",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Aliança, Cenários (ex: ordinian, liberation)",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 09:55:06",
    "name": "Rhed",
    "state": "RJ",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Presencial, Twilight Wars, Board Game Arena",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com desconhecidos em comunidades",
    "play_style": "Agressivo e focado em combate",
    "favorite_player_count": 4,
    "favorite_factions": "Sol, Mentak, Naalu",
    "least_favorite_factions": "Sardakk, Winnu, Yssaril",
    "expansions": "Jogo base apenas",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo, Mapas pré-criados",
    "setup_preference": "Mapas Pré-criados",
    "house_rules": "1 - Jogadores só podem se comunicar coom vizinhos (na verdade até onde eu entendi essas são as regras oficiais, mas aparentemente ninguém as usa, então parecem mais da casa do que oficiais)\n2 - Dois jogadores nunca podem possuir simultaneamente a mesma Nota Promissória um do outro (Support por Support, Ceasefire por Ceasefire, etc). Jogadores podem possuir notas promissórias diferentes (troca de Support por Ceasefire, por exemplo).\n3 - Não pode-se negociar mapa. (\"eu não te ataco ali, tu não me ataca aqui\", ou \"te deixo entrar nesse planeta aqui e você me dá X Tg\"). O restante é tudo negociável (leis, TGs, fragmentos, promissórias, momento de jogar cartas de estratégia, Speaker, etc)",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de tarde, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 10:09:59",
    "name": "Felipe Alice",
    "state": "SP",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "7h a 8h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Saar, Mentak, Yssaril",
    "least_favorite_factions": "Sol, L1z1x, Sardakk",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft, Como no manual do jogo",
    "setup_preference": "Milty",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 10:25:03",
    "name": "GBIS",
    "state": "ES",
    "age": "25-34",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Naalu, Yin, Vuil'Raith",
    "least_favorite_factions": "Sardakk, Mahact, Keleres",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "Milty draft",
    "house_rules": "Uma regra que adotamos para tornar as partidas mais rápidas e dinâmicas foi revelar mais de um objetivo público no início do jogo.\n\nNormalmente, apenas 1 objetivo público é revelado na rodada 2. Em nossa variante, revelamos 2 objetivos públicos nessa rodada. Isso aumenta as opções estratégicas para os jogadores desde o começo, acelera a pontuação e torna a partida mais dinâmica, e seguimos nessa logica nas rodads seguintes. ",
    "alternative_modes": "Cenários (ex: ordinian, liberation)",
    "championship_interest": "Talvez",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 10:40:07",
    "name": "Danilo",
    "state": "BA",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Sol, Yssaril, Nomad",
    "least_favorite_factions": "Nekro, Xxcha, Mahact",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 10:41:17",
    "name": "Cauã ",
    "state": "SP",
    "age": "18-24",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 5,
    "favorite_factions": "Arborec, Mahact, Firmament/Obsidian",
    "least_favorite_factions": "Letnev, Sol",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Talvez",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de tarde",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 10:41:33",
    "name": "",
    "state": "PR",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas, Espaço físico adequado para jogar",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 5,
    "favorite_factions": "Arborec, Muaat, Titans",
    "least_favorite_factions": "Mentak, Yin, Yssaril",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas aleatórios",
    "setup_preference": "Prefiro escolha livre de facção se possível",
    "house_rules": "Nós nao fazemos draft ou coisa do tipo, sempre decidimos tudo na hora sem no dado se necessário.",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Unica coisa que nao gosto quando vejo os drafts é a limitação excessiva em facções. O jogo possui tantas facções mas em um jogo de 6 pessoas a média é deixar até 9 facções no máximo. Isso é bem frustrante pra mim que nao jogo pensando em ter as melhores condições de facção slice e ordem de jogar. Eu jogo TI pela facção que gosto de jogar que são poucas, o resto nem me importo.",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 13:04:58",
    "name": "Igor",
    "state": "RR",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial, Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Muaat, Naalu, Vuil'Raith",
    "least_favorite_factions": "Winnu, Empyrean, Keleres",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall, Aliança, Cenários (ex: ordinian, liberation), Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 13:05:29",
    "name": "Natalia Avernus ",
    "state": "RJ",
    "age": "35-44",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Naalu, Xxcha, Yssaril",
    "least_favorite_factions": "Nekro, Sardakk, Firmament/Obsidian",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Jogo somente presencial",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 13:09:50",
    "name": "",
    "state": "MG",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "L1z1x, Yin, Naaz-Rokha",
    "least_favorite_factions": "Muaat, Mentak, Nomad",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft, Mapas pré-criados",
    "setup_preference": "Milty draft",
    "house_rules": "Não",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 1",
    "suggestions": "Não",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 13:11:04",
    "name": "Eduhenri",
    "state": "ES",
    "age": "45+",
    "experience": "Menos de 1 ano",
    "games_last_year": "1 a 3",
    "play_method": "Twilight Wars",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Falta de grupo/jogadores",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "L1z1x, Nekro, Jol-Nar",
    "least_favorite_factions": "Winnu, Yin, Yssaril",
    "expansions": "Jogo base apenas",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de tarde, Durante a semana, começando de noite/madrugada, Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 15:17:42",
    "name": "Thaillon Lemes",
    "state": "GO",
    "age": "25-34",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "6h a 7h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Muaat, Naalu, Sardakk",
    "least_favorite_factions": "",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Cenários (ex: ordinian, liberation), Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 15:50:40",
    "name": "",
    "state": "GO",
    "age": "35-44",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "Menos de 6h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Agressivo e focado em combate",
    "favorite_player_count": 4,
    "favorite_factions": "Arborec, Muaat, L1z1x",
    "least_favorite_factions": "Jol-Nar, Xxcha, Argent",
    "expansions": "Jogo base apenas",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Sexta-feira, começando de noite",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 17:04:10",
    "name": "",
    "state": "SP",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas, Falta de grupo/jogadores, Barreira financeira, Espaço físico adequado para jogar",
    "avg_duration": "Não jogo partidas ao vivo",
    "play_partners": "Com desconhecidos em comunidades",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Hacan, Empyrean, Naaz-Rokha",
    "least_favorite_factions": "Naalu, Argent, Vuil'Raith",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "12 pontos",
    "setup_decisions": "Milty draft, Nucleus draft",
    "setup_preference": "Nucleus draft",
    "house_rules": "Não",
    "alternative_modes": "Aliança",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Não",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 18:28:07",
    "name": "Abutzu",
    "state": "RJ",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "11 a 25",
    "play_method": "Tabletop Simulator, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "Menos de 6h",
    "play_partners": "Com desconhecidos em comunidades",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Naalu, Jol-Nar, Xxcha",
    "least_favorite_factions": "Saar, Yssaril",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "12 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 20:00:28",
    "name": "Marcio ",
    "state": "SP",
    "age": "18-24",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial, Tabletop Simulator, Tabletop Playground, Async TI Discord",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Nekro, Yin, Mahact",
    "least_favorite_factions": "",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Twilight's Fall, Aliança, Cenários (ex: ordinian, liberation), Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de tarde, Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Tabletop quando a maioria conseguir e async em último caso. ",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 21:59:33",
    "name": "m4skara-",
    "state": "PR",
    "age": "25-34",
    "experience": "Menos de 1 ano",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Sol, Yssaril, Mahact",
    "least_favorite_factions": "Arborec, Creuss, Sardakk",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "Não.",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-24 22:08:28",
    "name": "Monquinha",
    "state": "PE",
    "age": "25-34",
    "experience": "Menos de 1 ano",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "7h a 8h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 7,
    "favorite_factions": "Hacan, Titans, Vuil'Raith",
    "least_favorite_factions": "Arborec, Letnev, Yin",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-25 10:24:53",
    "name": "João 2",
    "state": "BA",
    "age": "25-34",
    "experience": "Menos de 1 ano",
    "games_last_year": "1 a 3",
    "play_method": "Tabletop Simulator",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores, Espaço físico adequado para jogar",
    "avg_duration": "7h a 8h",
    "play_partners": "Com desconhecidos em comunidades",
    "play_style": "Equilibrado",
    "favorite_player_count": 4,
    "favorite_factions": "Creuss, Nekro, Jol-Nar",
    "least_favorite_factions": "Naalu, Yin, Mahact",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-25 10:56:13",
    "name": "Joao Elso",
    "state": "GO",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Saar, Creuss, Yin",
    "least_favorite_factions": "Winnu, Xxcha, Firmament/Obsidian",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "Não pode usar ferramentas de negociação que oculte a negociação: WhatsApp, Whisper",
    "alternative_modes": "Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite, Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:20:48",
    "name": "Duann",
    "state": "SP",
    "age": "35-44",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial, Twilight Wars",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Falta de grupo/jogadores",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Jol-Nar, Nomad, Titans",
    "least_favorite_factions": "Sardakk",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "Nao",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:21:40",
    "name": "Clides",
    "state": "PE",
    "age": "25-34",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 7,
    "favorite_factions": "Letnev, Nekro, Naaz-Rokha",
    "least_favorite_factions": "Argent, Nomad, Crimson",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "12 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "não",
    "alternative_modes": "Twilight's Fall, Aliança",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:22:23",
    "name": "MatChan",
    "state": "SP",
    "age": "25-34",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Muaat, Sol, Titans",
    "least_favorite_factions": "Letnev",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "Estamos testando regras de como escolher os eventos, cada partida foi de um jeito. ",
    "alternative_modes": "Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Não",
    "availability": "",
    "championship_games_count": "",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:36:41",
    "name": "Arthur",
    "state": "SP",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Xxcha, Naaz-Rokha, Vuil'Raith",
    "least_favorite_factions": "Sardakk, Winnu, Keleres",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Não",
    "availability": "",
    "championship_games_count": "",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:45:38",
    "name": "",
    "state": "SP",
    "age": "25-34",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Saar, Mentak, Nomad",
    "least_favorite_factions": "Sol, Naalu, Xxcha",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Não",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:49:21",
    "name": "Luizprp",
    "state": "PA",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas, Falta de grupo/jogadores",
    "avg_duration": "8h a 9h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Xxcha, Titans, Vuil'Raith",
    "least_favorite_factions": "Muaat, Creuss, L1z1x",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft, Mapas pré-criados",
    "setup_preference": "Mapa pré criado",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada, Sexta-feira, começando de noite",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:51:02",
    "name": "",
    "state": "PA",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 8,
    "favorite_factions": "Arborec, Naalu, Nekro",
    "least_favorite_factions": "Letnev, Winnu, Yin",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "Mapas pré-criados pensando no balanceamento da galaxia.",
    "house_rules": "Não permitir dar apoio ao trono pra alguém que tem mais de 5 pontos.",
    "alternative_modes": "",
    "championship_interest": "Não",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 1",
    "suggestions": "Tem que ter balanceamento para ser justo num campeonato.",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 12:53:35",
    "name": "Maurício",
    "state": "SP",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial, Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Saar, Sol, Jol-Nar",
    "least_favorite_factions": "Arborec, Winnu, Argent",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "",
    "house_rules": "Não",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de tarde",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 13:04:49",
    "name": "Pedro",
    "state": "ES",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Tabletop Simulator",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Saar, Hacan, Yssaril",
    "least_favorite_factions": "Mentak, Winnu, Yin",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Durante a semana, começando de noite/madrugada, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 13:07:30",
    "name": "lucas mathias",
    "state": "SP",
    "age": "25-34",
    "experience": "Entre 1 a 3 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas, Espaço físico adequado para jogar",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "Muaat, Hacan, Winnu",
    "least_favorite_factions": "",
    "expansions": "Jogo base apenas",
    "points_goal": "12 pontos",
    "setup_decisions": "Milty draft, Como no manual do jogo",
    "setup_preference": "uma versão simplificada de milty draft. Todo mundo escolhe a facção com que quer jogar, e posiciona cada um na sua vez os tiles de mapa onde quiser",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de manhã, Fins de semana, começando de tarde",
    "championship_games_count": "Ao menos 2",
    "suggestions": "eu provavelmente não participaria por dificuldade de agenda, mas acho que seria muito legal se contasse com diversas partidas, ao menos três até decidir o campeão, e que variasse entre facção sorteada e facção escolhida pelo jogador",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 13:16:29",
    "name": "Max",
    "state": "PR",
    "age": "35-44",
    "experience": "Entre 4 e 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "L1z1x, Nekro, Vuil'Raith",
    "least_favorite_factions": "Winnu, Naaz-Rokha, Nomad",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Como no manual do jogo",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Não",
    "availability": "Fins de semana, começando de manhã",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 13:29:59",
    "name": "Lukano",
    "state": "PA",
    "age": "25-34",
    "experience": "Menos de 1 ano",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 4,
    "favorite_factions": "Nekro, Xxcha, Mahact",
    "least_favorite_factions": "Letnev, Nomad, Firmament/Obsidian",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "",
    "house_rules": "não",
    "alternative_modes": "Cenários (ex: ordinian, liberation)",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de tarde",
    "championship_games_count": "Ao menos 2",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 13:50:00",
    "name": "Botelho",
    "state": "PA",
    "age": "45+",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "Mais de 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Creuss, Nekro, Yssaril",
    "least_favorite_factions": "Letnev, Sol, Winnu",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "",
    "house_rules": "Não",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de tarde",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 14:53:59",
    "name": "",
    "state": "SP",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "4 a 10",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu)",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 6,
    "favorite_factions": "L1z1x, Xxcha, Yssaril",
    "least_favorite_factions": "Arborec",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Durante a semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 1",
    "suggestions": "Async",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 15:04:16",
    "name": "Leandro",
    "state": "PA",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Conciliação de agendas",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 8,
    "favorite_factions": "Arborec, Hacan, Naaz-Rokha",
    "least_favorite_factions": "Sardakk, Yin",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Sim",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-26 19:18:33",
    "name": "Danilo",
    "state": "BA",
    "age": "35-44",
    "experience": "Mais de 6 anos",
    "games_last_year": "1 a 3",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "6h a 7h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Equilibrado",
    "favorite_player_count": 5,
    "favorite_factions": "Letnev, Hacan, Yin",
    "least_favorite_factions": "Xxcha, Yssaril, Nomad",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "10 pontos",
    "setup_decisions": "Mapas pré-criados",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-27 09:42:15",
    "name": "Beast",
    "state": "RJ",
    "age": "45+",
    "experience": "Mais de 6 anos",
    "games_last_year": "Mais de 25",
    "play_method": "Presencial",
    "biggest_difficulty": "Falta de grupo/jogadores",
    "avg_duration": "Menos de 6h",
    "play_partners": "Com conhecidos casuais do hobby",
    "play_style": "Equilibrado",
    "favorite_player_count": 5,
    "favorite_factions": "Arborec, Nekro, Jol-Nar",
    "least_favorite_factions": "",
    "expansions": "Jogo base + Profecia dos Reis + Thunder's Edge",
    "points_goal": "10 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "Para reduzir o tempo (meu alvo e uma partida de 3H a 3:30H), sempre colocamos uma daptacao do Fast Start (agora inclusa no TE), e todos os objetivos aberto.",
    "alternative_modes": "Twilight's Fall, Aliança, Cenários (ex: ordinian, liberation), Eventos (ex: Total war, Age of exploration)",
    "championship_interest": "Não",
    "availability": "",
    "championship_games_count": "Quantas eu quiser/conseguir",
    "suggestions": "Partidas presencial com em torno de 3H a 3:30H. Possivelmente 3 ou 4 partidas por jogador em mesas distintas, totalizando os pontos na partida como criterio da formacao da mesa final.\n\nPessaolmente tiraria suporte ao trono, Heros, e o Breakthrough do jogo, por fazerem o jogo ficar muito Swingy.",
    "whatsapp": "",
    "email": ""
  },
  {
    "timestamp": "2026-06-27 13:00:31",
    "name": "Rafael",
    "state": "GO",
    "age": "25-34",
    "experience": "Mais de 6 anos",
    "games_last_year": "11 a 25",
    "play_method": "Presencial",
    "biggest_difficulty": "Disponibilidade de tempo (seu), Conciliação de agendas",
    "avg_duration": "8h a 9h",
    "play_partners": "Com um grupo fixo de amigos",
    "play_style": "Focado em negociação e diplomacia",
    "favorite_player_count": 6,
    "favorite_factions": "Saar, Mahact, Vuil'Raith",
    "least_favorite_factions": "Muaat, Winnu, Xxcha",
    "expansions": "Jogo base + Profecia dos Reis",
    "points_goal": "14 pontos",
    "setup_decisions": "Milty draft",
    "setup_preference": "",
    "house_rules": "",
    "alternative_modes": "",
    "championship_interest": "Talvez",
    "availability": "Sexta-feira, começando de noite, Fins de semana, começando de manhã, Fins de semana, começando de tarde, Fins de semana, começando de noite/madrugada",
    "championship_games_count": "Ao menos 1",
    "suggestions": "",
    "whatsapp": "",
    "email": ""
  }
];
